name: cppcheck-action-other_options-test

on:
  push:
  pull_request:

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # CppCheck analysis task
      # Task is expected to fail as code in __tests__ has a number of intentional issues
      - name: cppcheck
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_library: disable
          skip_preprocessor: disable
          enable: all #performance,portability,warning
          exclude_check: ./__tests__/exclude/
          inconclusive: disable
          inline_suppression: disable
          force_language: c
          force: enable
          max_ctu_depth: 12
          platform: disable
          #std: c11
          #output_file: ./CppCheckReport.txt
          other_options: --verbose --std=c11

